# Generated by Django 2.0.4 on 2018-08-05 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artical', '0002_auto_20180731_1947'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'verbose_name': 'MySubscriber', 'verbose_name_plural': 'A lot of Subscribers'},
        ),
    ]
